version: 0.2

phases:
  build:
    commands:
      - echo ECS Service update by Terraform
      - echo env $env
      - echo suffix $suffix
      - echo account $account
      - terraform init
      - terraform plan -var env=$env -var suffix=$suffix -var aws_region=us-east-1 -var account=$account -var ecs-image=public.ecr.aws/habukapperd/env-leaker-amd64
      - terraform apply -auto-approve -var env=$env -var suffix=$suffix -var account=$account -var ecs-image=public.ecr.aws/habukapperd/env-leaker-amd64
  post_build:
    commands:
      - echo Build completed on `date`

