version: 0.2

phases:
  build:
    commands:
      - echo ECS Service update by Terraform
      - echo env $env
      - echo suffix $suffix
      - echo account $account
      - terraform init
      - terraform import -var env=$env -var suffix=$suffix -var aws_region=$AWS_REGION -var account=$account -var ecs-image=$ecs_image aws_ecs_service.ecs_service um-${env}-${suffix}/um-${env}-${suffix}
      - terraform plan -var env=$env -var suffix=$suffix -var aws_region=$AWS_REGION -var account=$account -var ecs-image=$ecs_image
      - terraform apply -auto-approve -var env=$env -var suffix=$suffix -var aws_region=$AWS_REGION -var account=$account -var ecs-image=$ecs_image
  post_build:
    commands:
      - echo Build completed on `date`
      - cat terraform.tfstate

